name: euro_tube_app
description: A YouTube-like Flutter app
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.7.0
  chewie: ^1.7.0
  provider: ^6.1.0

flutter:
  uses-material-design: true
